name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-container:
    name: Build Docker Container image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build & Push Image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "ariessurya" --password-stdin
        docker image build -t ariessurya/suryaprakash-portfolio:latest .
        docker push ariessurya/suryaprakash-portfolio:latest
