name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-container:
    name: Build Docker Container image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Or your desired Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Angular Application
      run: npm run build -- --prod

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ariessurya/suryaprakash-portfolio:latest .

    - name: Push the Docker image
      run: docker push ariessurya/suryaprakash-portfolio:latest
